services:
  vrising:
    image: trueosiris/vrising
    tty: true
    stdin_open: true
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    environment:
      - TZ=America/New_York
      - SERVERNAME=vrising-Eithel
    volumes:
      - ./vrising-data:/data
